# This is a basic workflow to help you get started with Actions

name: Manylinux wheel build and upload to testypi

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell


      - uses: RalfG/python-wheels-manylinux-build@v0.4.2
        with:
          python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39 cp310-cp310'
      
      - name: List wheels
        # We're not going to need the linux_x86_64 wheels that are built.
        run: |
          sudo find dist -name '*linux_x86_64*' -delete
          ls dist
          
      - name: Build and Upload to TestPyPi
        run: |
          pip3 install twine
          python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}
          TWINE_REPOSITORY: testpypi
      - name: Test install of TestPyPi package
        run: | 
          pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple threedfa
          pip show threedfa
